services:
  web:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_BASE_URL=http://nginx:8000/api/v1
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/postgres

    networks:
      - custom_network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - custom_network
    depends_on:
      - db
      - vectordb
      - cache

  app:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - PORT=8080

      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/postgres
      - REDIS_URL=redis://cache:6379
      - CHROMA_HOST=vectordb
      - CHROMA_PORT=8000
    env_file:
      - ./app-backend/.env

    networks:
      - custom_network
    
    depends_on:
      - nginx

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    networks:
      - custom_network
      
    volumes:
      - db_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ":5432"
  
  cache:
    image: redis/redis-stack:latest
    ports:
      - ":6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis_data:/data
    networks:
      - custom_network
  
  vectordb:
    image: chromadb/chroma:latest
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_SERVER_HOST=vectordb
    ports:
      - ":8000"
    volumes:
      - vector_db_data:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  db_data:
  redis_data:
  vector_db_data:

networks:
  custom_network:
    driver: bridge