import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        port: '',
      }, { // Image generated by ModelsLab
        protocol: 'https',
        hostname: 'modelslab-bom.s3.amazonaws.com',
        port: '',
      },

      // Image sources for external images
      new URL('https://shutterstock.com/'),
      //new URL('https://www.pexels.com/'),
      { protocol: 'https', hostname: 'cdn.pixabay.com', port: '' },
      //new URL('https://cdn.pixabay.com/'),

      // Image CDN
      new URL(process.env.NEXT_PUBLIC_CLOUDFRONT || 'https://d26dkrocm93qz4.cloudfront.net')
    ]
    // domains: ['avatars.githubusercontent.com', 'modelslab-bom.s3.amazonaws.com', process.env.NEXT_PUBLIC_CLOUDFRONT || ''],
  },
  allowedDevOrigins: ["http://localhost:3000", "https://github.com"]
};

export default nextConfig;
